### ISSUE TITLE
Task 4

### ISSUE THREAD

**Issue by meamuri** [margarita-v/ParallelProgramming#1]
please, solve **task 4** and **task 5**. 

Other students want write perfect code too

**Comment by margarita-v** [comment]
@meamuri these tasks are in progress now and will be finished as soon as possible. Meanwhile you can check other perfect repos, for example, https://github.com/margarita-v/OpenGL-Sphere

**Comment by JohnReeze** [comment]
@margarita-v Now there is no use of other repos =(
